// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3uisCTEpdUAXtjPWeDWc078sZMQsYBmY',
    appId: '1:993630734123:web:41fc5cda38a318bb34676e',
    messagingSenderId: '993630734123',
    projectId: 'benefits-at-ease',
    authDomain: 'benefits-at-ease.firebaseapp.com',
    storageBucket: 'benefits-at-ease.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBejqsYOXGw5c2Z9n9X0M6uKUTqmLwM01I',
    appId: '1:993630734123:android:eaa5034e194e331c34676e',
    messagingSenderId: '993630734123',
    projectId: 'benefits-at-ease',
    storageBucket: 'benefits-at-ease.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRjcj7Ys-HG7ViSQIad-v1uLE-JsmXFLM',
    appId: '1:993630734123:ios:3ae879e0be78ce6334676e',
    messagingSenderId: '993630734123',
    projectId: 'benefits-at-ease',
    storageBucket: 'benefits-at-ease.appspot.com',
    iosClientId: '993630734123-diejddl858okiavg7tvsjbcq5fsbgmcn.apps.googleusercontent.com',
    iosBundleId: 'com.bae.bae',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRjcj7Ys-HG7ViSQIad-v1uLE-JsmXFLM',
    appId: '1:993630734123:ios:a8494c0b5f1ae7a534676e',
    messagingSenderId: '993630734123',
    projectId: 'benefits-at-ease',
    storageBucket: 'benefits-at-ease.appspot.com',
    iosClientId: '993630734123-3u67o6v2a1fnbukkksq349nfo7hsd28u.apps.googleusercontent.com',
    iosBundleId: 'com.bae.bae.RunnerTests',
  );
}
